spring:
  application:
    name: Pawction
  datasource:
    url: jdbc:mysql://localhost:3306/pawction?createDatabaseIfNotExist=true
    username: root
    password: Adhikari12
  jpa:
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 300KB
      max-request-size: 300KB
app:
  zone-id: "America/New_York"

auction:
  scheduler:
    enabled: true
    cron: "*/30 * * * * *"
    graceSeconds: 2
