spring:
  application:
    name: Pawction
  datasource:
    url: jdbc:mysql://localhost:3306/pawction?createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
  jpa:
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
