spring:
  application:
    name: Pawction
  datasource:
    url: jdbc:mysql://localhost:3306/pawaction?createDatabaseIfNotExist=true
    username: root
    password: shachin
  jpa:
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
app:
  zone-id: "America/New_York"

auction:
  scheduler:
    enabled: true
    cron: "*/30 * * * * *"
    graceSeconds: 2